Repository jungle-royale/jungle-royale-game-server, pull requests merged in 2025-01, with the labels that each got.

#42 fix: 플레이어 방향 수정, 청크 안떨어짐, 대시 안됨 수정
  calculator/calculator.go
  game/game.go
  message/message.pb.go
  message/message.proto
  object/physical/rectangle.go
  object/player.go
  state/state.go
Labels: 버그, 기능

#44 feat, fix: 타일 떨어지기 전 알림 기능 추가, 게임 시작 전 플레이어 죽는 문제 수정
  calculator/calculator.go
  game/game.go
  main.go
  message/message.pb.go
  message/message.proto
  object/tile.go
  state/state.go
  util/map.go
Labels: 버그, 기능

#46 feat: 게임 랭킹, 킬수 기능 구현
  calculator/calculator.go
  message/message.pb.go
  message/message.proto
  object/player.go
  util/map.go
Labels: 기능

#49 fix: 마이너 버그 수정
  game/game.go
  object/player.go
Labels: 버그

#50 fix: 대시 버그 수정
  object/player.go
Labels: 버그

#51 Issue34/game server engine 3
  object/player.go
Labels: 버그

#53 feat: 청크 사용 계산 구현
  calculator/calculator.go
  calculator/chunk.go
  chunk/chunk.go
  game/game.go
  main.go
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/healPack.go
  object/magic.go
  object/object.go
  object/player.go
  object/tile.go
  phaser-client/message.proto
  state/state.go
  test/package-lock.json
  test/package.json
  test/test.yaml
  test/tester.js
  util/set.go
Labels: 기능

#54 feat: 게임 서버 연동, 싱크맵 처리, main 실행인자 처리
  game/client.go
  game/client_message.go
  game/game.go
  game/game_manager.go
  main.go
  network/end_message_request.go
  network/game_server_notification_request.go
  network/start_message_request.go
Labels: 기능

#55 Issue52/http
  game/game.go
  game/game_manager.go
  main.go
Labels: 버그

#56 Issue client28/enemy move
  .gitignore
  calculator/calculator.go
  compile_protobuf.sh
  game/game.go
  game/game_manager.go
  message/message.pb.go
  message/message.proto
  object/player.go
  phaser-client/message.proto
  state/state.go
  test/load_test.yaml
  test/move_test.yaml
  test/tester.js
Labels: 기능

#58 feat: 순서대로 땅꺼짐 구현
  calculator/calculator.go
  game/game.go
  object/tile.go
  state/state.go
  test/move_test.yaml
  util/map.go
  util/set.go
Labels: 기능

#61 feat: 땅 없어질 때 위의 아이템도 사라지도록 구현
  calculator/calculator.go
  calculator/chunk.go
  game/game.go
  test/move_test.yaml
Labels: 기능

#63 fix: 서버에서 주는 Client Id 저장
  game/client.go
  game/game.go
  game/game_manager.go
Labels: 버그

#65 issue64/getItem-HeatBullet
  calculator/calculator.go
  compile_protobuf.sh
  cons/cons.go
  game/game.go
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/change.go
  object/magic.go
  object/player.go
  phaser-client/message.proto
  state/state.go
  test/load_test.yaml
  test/move_test.yaml
  util/set.go
Labels: 기능

#72 feat: reconnection
  game/client.go
  game/game.go
  game/game_manager.go
Labels: 기능

#77 feat: 원끼리 충돌시 서로 빗겨가도록 구현
  calculator/calculator.go
  calculator/chunk.go
  game/game.go
  object/bullet.go
  object/environment.go
  object/healPack.go
  object/magic.go
  object/physical/circle.go
  object/physical/physical.go
  object/physical/rectangle.go
  object/physical/rotRectangle.go
  object/player.go
  object/tile.go
  state/state.go
  test/temp_test.yaml
Labels: 기능

#80 feat: 사람, 총알과 물체 충돌 구현
  calculator/calculator.go
  cons/cons.go
  object/environment.go
  object/object.go
  object/physical/circle.go
  object/physical/rectangle.go
  object/tile.go
  state/state.go
Labels: 기능

#84 feat: 대기화면에서 총알 충돌처리 구현
  calculator/calculator.go
  game/game.go
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/change.go
  phaser-client/message.proto
Labels: 기능

#86 feat: 이동 상태, 대시 메시지 추가
  calculator/calculator.go
  message/message.pb.go
  message/message.proto
  object/change.go
  object/environment.go
  object/player.go
  object/tile.go
  phaser-client/message.proto
  state/state.go
Labels: 기능

#87 feat: 상태 메시지 좌표 추가
  calculator/calculator.go
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/change.go
  object/environment.go
  object/magic.go
  phaser-client/message.proto
  state/state.go
Labels: 기능

#89 Issue88/dash
  game/game_manager.go
  message/message.pb.go
  message/message.proto
  object/change.go
  object/player.go
  object/tile.go
  phaser-client/message.proto
  state/state.go
Labels: 버그, 기능

#91 fix: GameId "" 문제 수정
  game/client.go
  game/game_manager.go
Labels: 버그

#93 fix: 불마법 틱데미지 버그 수정
  calculator/calculator.go
  game/game.go
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/change.go
  object/player.go
  phaser-client/message.proto
Labels: 버그

#98 feat: 타일 부수기 알고리즘 수정
  calculator/calculator.go
  game/game.go
  object/tile.go
  state/state.go
  test/temp_test.yaml
Labels: 기능

#104 feat: 대기중인 플레이어 종료시 웹 서버로 알림
  game/game.go
  game/game_manager.go
  message/message.proto
  network/player_leave_message_request.go
  network/start_message_request.go
  object/change.go
  object/environment.go
  object/physical/circle.go
  state/state.go
  test/move_test.yaml
  test/temp_test.yaml
Labels: 기능

#106 feat: 떨어짐 판정 수정
  calculator/calculator.go
  calculator/chunk.go
  game/game.go
  game/game_manager.go
  network/start_message.go
  object/bullet.go
  object/environment.go
  object/healPack.go
  object/magic.go
  object/object.go
  object/player.go
  object/tile.go
  physical/circle.go
  physical/physical.go
  physical/rectangle.go
  physical/rotRectangle.go
Labels: 기능

#108 fix: deadstate 전송 버그 수정
  object/change.go
  phaser-client/message.proto
  test/package.json
  test/temp2_test.yaml
  test/tester.js
Labels: 버그

#110 feat: 대시 쿨타임, 지속 시간 변경
  object/player.go
Labels: 기능

#114 feat: 게임 종료 처리, TotalPlayerNum 메시지 필드 추가
  game/game.go
  game/game_manager.go
  message/message.pb.go
  message/message.proto
Labels: 기능

#116 fix: reconnection 버그 픽스
  game/game.go
  game/game_manager.go
Labels: 버그

#118 feat: 리커넥션 연결 처리
  game/game.go
  message/message.pb.go
  message/message.proto
Labels: 기능

#119 feat: Not Running 삭제
  game/game.go
Labels: 기능

#121 fix: 리커넥션 대기시간 3->1분 조정, 게임 종료 시 바로 종료 처리
  game/game.go
Labels: 버그

#127 feat: 게임 클라이언트 호스팅 부하 테스트
  test/page_test.yaml
Labels: 기능

#129 feat: broadcast 성능 개선 / broadcast 빈도 낮춤
  cons/cons.go
  game/client.go
  game/game.go
  game/game_manager.go
  test_py/test.py
Labels: 기능

#132 feat: gamestate에 player 이동량 추가
  message/message.pb.go
  message/message.proto
  object/player.go
  phaser-client/message.proto
  test_py/message.proto
  test_py/message_pb2.py
  test_py/test.py
Labels: 기능

#134 feat: 총알 게이지 기능 추가
  message/message.pb.go
  message/message.proto
  object/bullet.go
  object/player.go
  phaser-client/message.proto
  test_py/__pycache__/message_pb2.cpython-310.pyc
  test_py/message.proto
  test_py/message_pb2.py
Labels: 기능

#136 feat: 관전모드 구현
  game/client.go
  game/game.go
  game/game_manager.go
  object/environment.go
  object/player.go
  test_py/test.py
Labels: 기능

#138 feat: check-all-game api
  game/game.go
  game/game_manager.go
  game/server_manager.go
  serverlog/server_logger.go
  state/state.go
Labels: 기능

#140 feat: 마법 횟수제한 기능
  object/player.go
Labels: 기능

#142 feat: 게임 내 닉네임 추가
  game/client.go
  game/game.go
  game/game_manager.go
  message/message.pb.go
  message/message.proto
  phaser-client/message.proto
  test_py/message.proto
Labels: 기능

#143 feat: 게임 확인 api
  game/server_manager.go
  object/player.go
  test_py/__pycache__/message_pb2.cpython-310.pyc
  test_py/test.py
Labels: 기능

#144 feat: 서버 시간 수정
  game/game.go
  message/message.pb.go
  message/message.proto
  test_py/message_pb2.py
Labels: 기능

#146 feat: 쿨타임 조정
  object/player.go
Labels: 기능

#148 fix: 리커넥션 에러 수정
  game/game.go
Labels: 버그

#150 feat: 게임 강제시작 기능 구현
  game/game.go
  game/server_manager.go
  message/message.pb.go
  message/message.proto
  test_py/__pycache__/message_pb2.cpython-310.pyc
  test_py/test.py
Labels: 기능

#151 feat: 기능 버그 수정
  game/client.go
  game/game.go
  game/server_manager.go
  object/environment.go
  object/player.go
  state/state.go
  test_py/test.py
Labels: 버그

#152 fix: 버그 수정
  game/client.go
  game/game.go
  test_py/test.py
Labels: 버그

#154 feat: 인게임 킬수 확인 기능 추가
  message/message.pb.go
  message/message.proto
  object/player.go
  state/state.go
Labels: 기능

#156 fix: 연결이 끊긴 클아이언트에 쓰기 시도하는 버그 수정
  game/client.go
  test_py/__pycache__/message_pb2.cpython-310.pyc
  test_py/test.py
Labels: 버그

#158 fix: 여러 고루틴에서 client.close 호출되는 버그 수정
  game/client.go
Labels: 버그

#159 fix: 클라이언트 쓰기 버그 수정
  game/client.go
  test_py/test.py
Labels: 버그

#163 fix: 최소인원 이상 인원 접속시 첫번쨰 접속자 튕기는 버그 수정
  game/client.go
  game/game.go
  game/game_manager.go
Labels: 버그

#168 fix: 대기화면 시간초
  game/game.go
  object/bullet.go
Labels: 버그

#169 fix: 게임 시간 버그 수정
  state/state.go
Labels: 버그
